### ISSUE TITLE
ForceUI - Issues importing DatePicker component

### ISSUE THREAD

**Issue by bsfkaustubh** [brainstormforce/force-ui#179]
## Description

I'm trying to import DatePicker in ZipWP which uses Next.js. I'm facing these two issues:
1. Import suggestions not available
Directly declaring any component and using import suggestions does not return suggestions for ForceUI - https://d.pr/v/yPBnEY 

2. 'window is not defined' error when importing a component in Next.js
Tried to import <DatePicker /> from @bsf/force-ui and it returns the error. https://d.pr/v/yPBnEY 1:33

## Step-by-step reproduction instructions

https://d.pr/v/yPBnEY

## Expected behaviour

1. Need import suggestions for good DX
2. Fix the window is not defined' error when importing component

## Screenshots or screen recording (optional)

https://d.pr/v/yPBnEY

**Comment by vrundakansara** [comment]
Fixed in #183
